import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const kumbhSans = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>{children}</body>
    </html>
  );
}
